# Generated by Django 6.0.4 on 2026-05-05 21:18

from django.db import migrations, models

import core.services.file_service


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profilemodel_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=core.services.file_service.FileService.upload_avatar),
        ),
    ]
