# Generated by Django 6.0.4 on 2026-05-05 21:18

from django.db import migrations, models

import core.services.file_service


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_carmodel_body_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='car_photo',
            field=models.ImageField(blank=True, upload_to=core.services.file_service.FileService.upload_car_photo),
        ),
    ]
