# Generated by Django 6.0.4 on 2026-04-22 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='autoparkmodel',
            table='auto_parks',
        ),
    ]
