# Generated by Django 6.0.4 on 2026-04-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('seat_count', models.IntegerField()),
                ('body_type', models.CharField(max_length=20)),
                ('engine_volume', models.FloatField()),
            ],
            options={
                'db_table': 'cars_hm1',
            },
        ),
    ]
